### ISSUE TITLE
Please make the cz-Viator-rotor and ring version for windows

### ISSUE THREAD

**Issue by Tushar-Faroque** [charakterziffer/cursor-toolbox#1]
Please make the cz-Viator-rotor and ring version for windows, I am using the rotor in my Ubuntu and want to use it in windows 10. I was unable to do it using the GitHub repository.
Thanks.

**Comment by charakterziffer** [comment]
Thank you for your request. For Windows you need the [Real World Cursor Editor](http://www.rw-designer.com/cursor-maker) to combine the PNG images to a cursor theme. I’ve done this on the computer of a friend because I myself don’t have Windows.

Would it help if I render the neccessary PNG images for you so you could import them into the Cursor Editor?

**Comment by Tushar-Faroque** [comment]
Yes, please 
it would be a great help.

**Comment by charakterziffer** [comment]
Here are all the possible PNG images of my cursor theme cz-Viator: [czViator_all-pngs.zip](https://github.com/charakterziffer/cursor-toolbox/files/4353047/czViator_all-pngs.zip). I rendered them without shadows so you could use the equivalent setting of Windows 10 as you like. In the package there are three different sizes, if you like to create size variable cursors with layers.

If you like to, you could upload your final work here and I make it available for all users (of course with credit for you).

**Comment by Tushar-Faroque** [comment]
Thanks a lot
Yeah I will do that.
